# permissions for end users to edit gitlabs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: gitlab-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: gitlab-operator
    app.kubernetes.io/part-of: gitlab-operator
    app.kubernetes.io/managed-by: kustomize
  name: gitlab-editor-role
rules:
- apiGroups:
  - apps.mycompany.com
  resources:
  - gitlabs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.mycompany.com
  resources:
  - gitlabs/status
  verbs:
  - get
